spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 43q21
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
logging:
  level:
    org.zalando.logbook: TRACE